export const ActionConstants = {
    FIREBASE_LOGIN : "FIREBASE_LOGIN",
    FIREBASE_SIGNUP : "FIREBASE_SIGNUP",
    SET_FIREBASE_USER : "SET_FIREBASE_USER",
    UPDATE_LOGIN_STATUS : "UPDATE_LOGIN_STATUS",
}