export const ActionConstants = {
    FIREBASE_LOGIN : "FIREBASE_LOGIN",
    FIREBASE_SIGNUP : "FIREBASE_SIGNUP",
    SET_FIREBASE_USER : "SET_FIREBASE_USER",
    ADD_USER_ID : "ADD_USER_ID",
    UPDATE_LOGIN_STATUS : "UPDATE_LOGIN_STATUS",
    UPDATE_CURRENT_USER_PROFILE : "UPDATE_CURRENT_USER_PROFILE",
    UPDATE_AVAILABLE_USER_LIST : "UPDATE_AVAILABLE_USER_LIST",
    UPDATE_NEW_ACCOUNT : "UPDATE_NEW_ACCOUNT",
    STORE_CURRENT_USER_PROFILE : "STORE_CURRENT_USER_PROFILE",
    ADD_AVAILABLE_USER_LIST : "ADD_AVAILABLE_USER_LIST",
}